import 'dart:core';

import 'package:device_info/device_info.dart';
import 'package:flutter_fhir/fhirClasses/period.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:path_provider/path_provider.dart';

classesSetup() async {
  List<String> types = [
    'Element',
    'Extension',
    'Narrative',
    'Annotation',
    'Attachment',
    'Identifier',
    'CodeableConcept',
    'Coding',
    'Quantity',
    'Duration',
    'Distance',
    'Count',
    'Money',
    'Age',
    'Range',
    'Period',
    'Ratio',
    'Reference',
    'SampledData',
    'Signature',
    'HumanName',
    'Address',
    'ContactPoint',
    'Timing',
    'Timing_Repeat',
    'Meta',
    'ContactDetail',
    'Contributor',
    'DataRequirement',
    'DataRequirement_CodeFilter',
    'DataRequirement_DateFilter',
    'DataRequirement_Sort',
    'ParameterDefinition',
    'RelatedArtifact',
    'TriggerDefinition',
    'UsageContext',
    'Dosage',
    'Dosage_DoseAndRate',
    'Population',
    'ProductShelfLife',
    'ProdCharacteristic',
    'MarketingStatus',
    'SubstanceAmount',
    'SubstanceAmount_ReferenceRange',
    'Expression',
    'ElementDefinition',
    'ElementDefinition_Slicing',
    'ElementDefinition_Discriminator',
    'ElementDefinition_Base',
    'ElementDefinition_Type',
    'ElementDefinition_Example',
    'ElementDefinition_Constraint',
    'ElementDefinition_Binding',
    'ElementDefinition_Mapping',
    'Account',
    'Account_Coverage',
    'Account_Guarantor',
    'ActivityDefinition',
    'ActivityDefinition_Participant',
    'ActivityDefinition_DynamicValue',
    'AdverseEvent',
    'AdverseEvent_SuspectEntity',
    'AdverseEvent_Causality',
    'AllergyIntolerance',
    'AllergyIntolerance_Reaction',
    'Appointment',
    'Appointment_Participant',
    'AppointmentResponse',
    'AuditEvent',
    'AuditEvent_Agent',
    'AuditEvent_Network',
    'AuditEvent_Source',
    'AuditEvent_Entity',
    'AuditEvent_Detail',
    'Basic',
    'Binary',
    'BiologicallyDerivedProduct',
    'BiologicallyDerivedProduct_Collection',
    'BiologicallyDerivedProduct_Processing',
    'BiologicallyDerivedProduct_Manipulation',
    'BiologicallyDerivedProduct_Storage',
    'BodyStructure',
    'Bundle',
    'Bundle_Link',
    'Bundle_Entry',
    'Bundle_Search',
    'Bundle_Request',
    'Bundle_Response',
    'CapabilityStatement',
    'CapabilityStatement_Software',
    'CapabilityStatement_Implementation',
    'CapabilityStatement_Rest',
    'CapabilityStatement_Security',
    'CapabilityStatement_Resource',
    'CapabilityStatement_Interaction',
    'CapabilityStatement_SearchParam',
    'CapabilityStatement_Operation',
    'CapabilityStatement_Interaction1',
    'CapabilityStatement_Messaging',
    'CapabilityStatement_Endpoint',
    'CapabilityStatement_SupportedMessage',
    'CapabilityStatement_Document',
    'CarePlan',
    'CarePlan_Activity',
    'CarePlan_Detail',
    'CareTeam',
    'CareTeam_Participant',
    'CatalogEntry',
    'CatalogEntry_RelatedEntry',
    'ChargeItem',
    'ChargeItem_Performer',
    'ChargeItemDefinition',
    'ChargeItemDefinition_Applicability',
    'ChargeItemDefinition_PropertyGroup',
    'ChargeItemDefinition_PriceComponent',
    'Claim',
    'Claim_Related',
    'Claim_Payee',
    'Claim_CareTeam',
    'Claim_SupportingInfo',
    'Claim_Diagnosis',
    'Claim_Procedure',
    'Claim_Insurance',
    'Claim_Accident',
    'Claim_Item',
    'Claim_Detail',
    'Claim_SubDetail',
    'ClaimResponse',
    'ClaimResponse_Item',
    'ClaimResponse_Adjudication',
    'ClaimResponse_Detail',
    'ClaimResponse_SubDetail',
    'ClaimResponse_AddItem',
    'ClaimResponse_Detail1',
    'ClaimResponse_SubDetail1',
    'ClaimResponse_Total',
    'ClaimResponse_Payment',
    'ClaimResponse_ProcessNote',
    'ClaimResponse_Insurance',
    'ClaimResponse_Error',
    'ClinicalImpression',
    'ClinicalImpression_Investigation',
    'ClinicalImpression_Finding',
    'CodeSystem',
    'CodeSystem_Filter',
    'CodeSystem_Property',
    'CodeSystem_Concept',
    'CodeSystem_Designation',
    'CodeSystem_Property1',
    'Communication',
    'Communication_Payload',
    'CommunicationRequest',
    'CommunicationRequest_Payload',
    'CompartmentDefinition',
    'CompartmentDefinition_Resource',
    'Composition',
    'Composition_Attester',
    'Composition_RelatesTo',
    'Composition_Event',
    'Composition_Section',
    'ConceptMap',
    'ConceptMap_Group',
    'ConceptMap_Element',
    'ConceptMap_Target',
    'ConceptMap_DependsOn',
    'ConceptMap_Unmapped',
    'Condition',
    'Condition_Stage',
    'Condition_Evidence',
    'Consent',
    'Consent_Policy',
    'Consent_Verification',
    'Consent_Provision',
    'Consent_Actor',
    'Consent_Data',
    'Contract',
    'Contract_ContentDefinition',
    'Contract_Term',
    'Contract_SecurityLabel',
    'Contract_Offer',
    'Contract_Party',
    'Contract_Answer',
    'Contract_Asset',
    'Contract_Context',
    'Contract_ValuedItem',
    'Contract_Action',
    'Contract_Subject',
    'Contract_Signer',
    'Contract_Friendly',
    'Contract_Legal',
    'Contract_Rule',
    'Coverage',
    'Coverage_Class',
    'Coverage_CostToBeneficiary',
    'Coverage_Exception',
    'CoverageEligibilityRequest',
    'CoverageEligibilityRequest_SupportingInfo',
    'CoverageEligibilityRequest_Insurance',
    'CoverageEligibilityRequest_Item',
    'CoverageEligibilityRequest_Diagnosis',
    'CoverageEligibilityResponse',
    'CoverageEligibilityResponse_Insurance',
    'CoverageEligibilityResponse_Item',
    'CoverageEligibilityResponse_Benefit',
    'CoverageEligibilityResponse_Error',
    'DetectedIssue',
    'DetectedIssue_Evidence',
    'DetectedIssue_Mitigation',
    'Device',
    'Device_UdiCarrier',
    'Device_DeviceName',
    'Device_Specialization',
    'Device_Version',
    'Device_Property',
    'DeviceDefinition',
    'DeviceDefinition_UdiDeviceIdentifier',
    'DeviceDefinition_DeviceName',
    'DeviceDefinition_Specialization',
    'DeviceDefinition_Capability',
    'DeviceDefinition_Property',
    'DeviceDefinition_Material',
    'DeviceMetric',
    'DeviceMetric_Calibration',
    'DeviceRequest',
    'DeviceRequest_Parameter',
    'DeviceUseStatement',
    'DiagnosticReport',
    'DiagnosticReport_Media',
    'DocumentManifest',
    'DocumentManifest_Related',
    'DocumentReference',
    'DocumentReference_RelatesTo',
    'DocumentReference_Content',
    'DocumentReference_Context',
    'EffectEvidenceSynthesis',
    'EffectEvidenceSynthesis_SampleSize',
    'EffectEvidenceSynthesis_ResultsByExposure',
    'EffectEvidenceSynthesis_EffectEstimate',
    'EffectEvidenceSynthesis_PrecisionEstimate',
    'EffectEvidenceSynthesis_Certainty',
    'EffectEvidenceSynthesis_CertaintySubcomponent',
    'Encounter',
    'Encounter_StatusHistory',
    'Encounter_ClassHistory',
    'Encounter_Participant',
    'Encounter_Diagnosis',
    'Encounter_Hospitalization',
    'Encounter_Location',
    'Endpoint',
    'EnrollmentRequest',
    'EnrollmentResponse',
    'EpisodeOfCare',
    'EpisodeOfCare_StatusHistory',
    'EpisodeOfCare_Diagnosis',
    'EventDefinition',
    'Evidence',
    'EvidenceVariable',
    'EvidenceVariable_Characteristic',
    'ExampleScenario',
    'ExampleScenario_Actor',
    'ExampleScenario_Instance',
    'ExampleScenario_Version',
    'ExampleScenario_ContainedInstance',
    'ExampleScenario_Process',
    'ExampleScenario_Step',
    'ExampleScenario_Operation',
    'ExampleScenario_Alternative',
    'ExplanationOfBenefit',
    'ExplanationOfBenefit_Related',
    'ExplanationOfBenefit_Payee',
    'ExplanationOfBenefit_CareTeam',
    'ExplanationOfBenefit_SupportingInfo',
    'ExplanationOfBenefit_Diagnosis',
    'ExplanationOfBenefit_Procedure',
    'ExplanationOfBenefit_Insurance',
    'ExplanationOfBenefit_Accident',
    'ExplanationOfBenefit_Item',
    'ExplanationOfBenefit_Adjudication',
    'ExplanationOfBenefit_Detail',
    'ExplanationOfBenefit_SubDetail',
    'ExplanationOfBenefit_AddItem',
    'ExplanationOfBenefit_Detail1',
    'ExplanationOfBenefit_SubDetail1',
    'ExplanationOfBenefit_Total',
    'ExplanationOfBenefit_Payment',
    'ExplanationOfBenefit_ProcessNote',
    'ExplanationOfBenefit_BenefitBalance',
    'ExplanationOfBenefit_Financial',
    'FamilyMemberHistory',
    'FamilyMemberHistory_Condition',
    'Flag',
    'Goal',
    'Goal_Target',
    'GraphDefinition',
    'GraphDefinition_Link',
    'GraphDefinition_Target',
    'GraphDefinition_Compartment',
    'Group',
    'Group_Characteristic',
    'Group_Member',
    'GuidanceResponse',
    'HealthcareService',
    'HealthcareService_Eligibility',
    'HealthcareService_AvailableTime',
    'HealthcareService_NotAvailable',
    'ImagingStudy',
    'ImagingStudy_Series',
    'ImagingStudy_Performer',
    'ImagingStudy_Instance',
    'Immunization',
    'Immunization_Performer',
    'Immunization_Education',
    'Immunization_Reaction',
    'Immunization_ProtocolApplied',
    'ImmunizationEvaluation',
    'ImmunizationRecommendation',
    'ImmunizationRecommendation_Recommendation',
    'ImmunizationRecommendation_DateCriterion',
    'ImplementationGuide',
    'ImplementationGuide_DependsOn',
    'ImplementationGuide_Global',
    'ImplementationGuide_Definition',
    'ImplementationGuide_Grouping',
    'ImplementationGuide_Resource',
    'ImplementationGuide_Page',
    'ImplementationGuide_Parameter',
    'ImplementationGuide_Template',
    'ImplementationGuide_Manifest',
    'ImplementationGuide_Resource1',
    'ImplementationGuide_Page1',
    'InsurancePlan',
    'InsurancePlan_Contact',
    'InsurancePlan_Coverage',
    'InsurancePlan_Benefit',
    'InsurancePlan_Limit',
    'InsurancePlan_Plan',
    'InsurancePlan_GeneralCost',
    'InsurancePlan_SpecificCost',
    'InsurancePlan_Benefit1',
    'InsurancePlan_Cost',
    'Invoice',
    'Invoice_Participant',
    'Invoice_LineItem',
    'Invoice_PriceComponent',
    'Library',
    'Linkage',
    'Linkage_Item',
    'Lists',
    'List_Entry',
    'Location',
    'Location_Position',
    'Location_HoursOfOperation',
    'Measure',
    'Measure_Group',
    'Measure_Population',
    'Measure_Stratifier',
    'Measure_Component',
    'Measure_SupplementalData',
    'MeasureReport',
    'MeasureReport_Group',
    'MeasureReport_Population',
    'MeasureReport_Stratifier',
    'MeasureReport_Stratum',
    'MeasureReport_Component',
    'MeasureReport_Population1',
    'Media',
    'Medication',
    'Medication_Ingredient',
    'Medication_Batch',
    'MedicationAdministration',
    'MedicationAdministration_Performer',
    'MedicationAdministration_Dosage',
    'MedicationDispense',
    'MedicationDispense_Performer',
    'MedicationDispense_Substitution',
    'MedicationKnowledge',
    'MedicationKnowledge_RelatedMedicationKnowledge',
    'MedicationKnowledge_Monograph',
    'MedicationKnowledge_Ingredient',
    'MedicationKnowledge_Cost',
    'MedicationKnowledge_MonitoringProgram',
    'MedicationKnowledge_AdministrationGuidelines',
    'MedicationKnowledge_Dosage',
    'MedicationKnowledge_PatientCharacteristics',
    'MedicationKnowledge_MedicineClassification',
    'MedicationKnowledge_Packaging',
    'MedicationKnowledge_DrugCharacteristic',
    'MedicationKnowledge_Regulatory',
    'MedicationKnowledge_Substitution',
    'MedicationKnowledge_Schedule',
    'MedicationKnowledge_MaxDispense',
    'MedicationKnowledge_Kinetics',
    'MedicationRequest',
    'MedicationRequest_DispenseRequest',
    'MedicationRequest_InitialFill',
    'MedicationRequest_Substitution',
    'MedicationStatement',
    'MedicinalProduct',
    'MedicinalProduct_Name',
    'MedicinalProduct_NamePart',
    'MedicinalProduct_CountryLanguage',
    'MedicinalProduct_ManufacturingBusinessOperation',
    'MedicinalProduct_SpecialDesignation',
    'MedicinalProductAuthorization',
    'MedicinalProductAuthorization_JurisdictionalAuthorization',
    'MedicinalProductAuthorization_Procedure',
    'MedicinalProductContraindication',
    'MedicinalProductContraindication_OtherTherapy',
    'MedicinalProductIndication',
    'MedicinalProductIndication_OtherTherapy',
    'MedicinalProductIngredient',
    'MedicinalProductIngredient_SpecifiedSubstance',
    'MedicinalProductIngredient_Strength',
    'MedicinalProductIngredient_ReferenceStrength',
    'MedicinalProductIngredient_Substance',
    'MedicinalProductInteraction',
    'MedicinalProductInteraction_Interactant',
    'MedicinalProductManufactured',
    'MedicinalProductPackaged',
    'MedicinalProductPackaged_BatchIdentifier',
    'MedicinalProductPackaged_PackageItem',
    'MedicinalProductPharmaceutical',
    'MedicinalProductPharmaceutical_Characteristics',
    'MedicinalProductPharmaceutical_RouteOfAdministration',
    'MedicinalProductPharmaceutical_TargetSpecies',
    'MedicinalProductPharmaceutical_WithdrawalPeriod',
    'MedicinalProductUndesirableEffect',
    'MessageDefinition',
    'MessageDefinition_Focus',
    'MessageDefinition_AllowedResponse',
    'MessageHeader',
    'MessageHeader_Destination',
    'MessageHeader_Source',
    'MessageHeader_Response',
    'MolecularSequence',
    'MolecularSequence_ReferenceSeq',
    'MolecularSequence_Variant',
    'MolecularSequence_Quality',
    'MolecularSequence_Roc',
    'MolecularSequence_Repository',
    'MolecularSequence_StructureVariant',
    'MolecularSequence_Outer',
    'MolecularSequence_Inner',
    'NamingSystem',
    'NamingSystem_UniqueId',
    'NutritionOrder',
    'NutritionOrder_OralDiet',
    'NutritionOrder_Nutrient',
    'NutritionOrder_Texture',
    'NutritionOrder_Supplement',
    'NutritionOrder_EnteralFormula',
    'NutritionOrder_Administration',
    'Observation',
    'Observation_ReferenceRange',
    'Observation_Component',
    'ObservationDefinition',
    'ObservationDefinition_QuantitativeDetails',
    'ObservationDefinition_QualifiedInterval',
    'OperationDefinition',
    'OperationDefinition_Parameter',
    'OperationDefinition_Binding',
    'OperationDefinition_ReferencedFrom',
    'OperationDefinition_Overload',
    'OperationOutcome',
    'OperationOutcome_Issue',
    'Organization',
    'Organization_Contact',
    'OrganizationAffiliation',
    'Parameters',
    'Parameters_Parameter',
    'Patient',
    'Patient_Contact',
    'Patient_Communication',
    'Patient_Link',
    'PaymentNotice',
    'PaymentReconciliation',
    'PaymentReconciliation_Detail',
    'PaymentReconciliation_ProcessNote',
    'Person',
    'Person_Link',
    'PlanDefinition',
    'PlanDefinition_Goal',
    'PlanDefinition_Target',
    'PlanDefinition_Action',
    'PlanDefinition_Condition',
    'PlanDefinition_RelatedAction',
    'PlanDefinition_Participant',
    'PlanDefinition_DynamicValue',
    'Practitioner',
    'Practitioner_Qualification',
    'PractitionerRole',
    'PractitionerRole_AvailableTime',
    'PractitionerRole_NotAvailable',
    'Procedure',
    'Procedure_Performer',
    'Procedure_FocalDevice',
    'Provenance',
    'Provenance_Agent',
    'Provenance_Entity',
    'Questionnaire',
    'Questionnaire_Item',
    'Questionnaire_EnableWhen',
    'Questionnaire_AnswerOption',
    'Questionnaire_Initial',
    'QuestionnaireResponse',
    'QuestionnaireResponse_Item',
    'QuestionnaireResponse_Answer',
    'RelatedPerson',
    'RelatedPerson_Communication',
    'RequestGroup',
    'RequestGroup_Action',
    'RequestGroup_Condition',
    'RequestGroup_RelatedAction',
    'ResearchDefinition',
    'ResearchElementDefinition',
    'ResearchElementDefinition_Characteristic',
    'ResearchStudy',
    'ResearchStudy_Arm',
    'ResearchStudy_Objective',
    'ResearchSubject',
    'RiskAssessment',
    'RiskAssessment_Prediction',
    'RiskEvidenceSynthesis',
    'RiskEvidenceSynthesis_SampleSize',
    'RiskEvidenceSynthesis_RiskEstimate',
    'RiskEvidenceSynthesis_PrecisionEstimate',
    'RiskEvidenceSynthesis_Certainty',
    'RiskEvidenceSynthesis_CertaintySubcomponent',
    'Schedule',
    'SearchParameter',
    'SearchParameter_Component',
    'ServiceRequest',
    'Slot',
    'Specimen',
    'Specimen_Collection',
    'Specimen_Processing',
    'Specimen_Container',
    'SpecimenDefinition',
    'SpecimenDefinition_TypeTested',
    'SpecimenDefinition_Container',
    'SpecimenDefinition_Additive',
    'SpecimenDefinition_Handling',
    'StructureDefinition',
    'StructureDefinition_Mapping',
    'StructureDefinition_Context',
    'StructureDefinition_Snapshot',
    'StructureDefinition_Differential',
    'StructureMap',
    'StructureMap_Structure',
    'StructureMap_Group',
    'StructureMap_Input',
    'StructureMap_Rule',
    'StructureMap_Source',
    'StructureMap_Target',
    'StructureMap_Parameter',
    'StructureMap_Dependent',
    'Subscription',
    'Subscription_Channel',
    'Substance',
    'Substance_Instance',
    'Substance_Ingredient',
    'SubstanceNucleicAcid',
    'SubstanceNucleicAcid_Subunit',
    'SubstanceNucleicAcid_Linkage',
    'SubstanceNucleicAcid_Sugar',
    'SubstancePolymer',
    'SubstancePolymer_MonomerSet',
    'SubstancePolymer_StartingMaterial',
    'SubstancePolymer_Repeat',
    'SubstancePolymer_RepeatUnit',
    'SubstancePolymer_DegreeOfPolymerisation',
    'SubstancePolymer_StructuralRepresentation',
    'SubstanceProtein',
    'SubstanceProtein_Subunit',
    'SubstanceReferenceInformation',
    'SubstanceReferenceInformation_Gene',
    'SubstanceReferenceInformation_GeneElement',
    'SubstanceReferenceInformation_Classification',
    'SubstanceReferenceInformation_Target',
    'SubstanceSourceMaterial',
    'SubstanceSourceMaterial_FractionDescription',
    'SubstanceSourceMaterial_Organism',
    'SubstanceSourceMaterial_Author',
    'SubstanceSourceMaterial_Hybrid',
    'SubstanceSourceMaterial_OrganismGeneral',
    'SubstanceSourceMaterial_PartDescription',
    'SubstanceSpecification',
    'SubstanceSpecification_Moiety',
    'SubstanceSpecification_Property',
    'SubstanceSpecification_Structure',
    'SubstanceSpecification_Isotope',
    'SubstanceSpecification_MolecularWeight',
    'SubstanceSpecification_Representation',
    'SubstanceSpecification_Code',
    'SubstanceSpecification_Name',
    'SubstanceSpecification_Official',
    'SubstanceSpecification_Relationship',
    'SupplyDelivery',
    'SupplyDelivery_SuppliedItem',
    'SupplyRequest',
    'SupplyRequest_Parameter',
    'Task',
    'Task_Restriction',
    'Task_Input',
    'Task_Output',
    'TerminologyCapabilities',
    'TerminologyCapabilities_Software',
    'TerminologyCapabilities_Implementation',
    'TerminologyCapabilities_CodeSystem',
    'TerminologyCapabilities_Version',
    'TerminologyCapabilities_Filter',
    'TerminologyCapabilities_Expansion',
    'TerminologyCapabilities_Parameter',
    'TerminologyCapabilities_ValidateCode',
    'TerminologyCapabilities_Translation',
    'TerminologyCapabilities_Closure',
    'TestReport',
    'TestReport_Participant',
    'TestReport_Setup',
    'TestReport_Action',
    'TestReport_Operation',
    'TestReport_Assert',
    'TestReport_Test',
    'TestReport_Action1',
    'TestReport_Teardown',
    'TestReport_Action2',
    'TestScript',
    'TestScript_Origin',
    'TestScript_Destination',
    'TestScript_Metadata',
    'TestScript_Link',
    'TestScript_Capability',
    'TestScript_Fixture',
    'TestScript_Variable',
    'TestScript_Setup',
    'TestScript_Action',
    'TestScript_Operation',
    'TestScript_RequestHeader',
    'TestScript_Assert',
    'TestScript_Test',
    'TestScript_Action1',
    'TestScript_Teardown',
    'TestScript_Action2',
    'ValueSet',
    'ValueSet_Compose',
    'ValueSet_Include',
    'ValueSet_Concept',
    'ValueSet_Designation',
    'ValueSet_Filter',
    'ValueSet_Expansion',
    'ValueSet_Parameter',
    'ValueSet_Contains',
    'VerificationResult',
    'VerificationResult_PrimarySource',
    'VerificationResult_Attestation',
    'VerificationResult_Validator',
    'VisionPrescription',
    'VisionPrescription_LensSpecification',
    'VisionPrescription_Prism'
  ];

  Hive.registerAdapter(ClassesAdapter());
  final appDocumentDir = await getApplicationDocumentsDirectory();
  Hive.init(appDocumentDir.path);
  var classesBox = await Hive.openBox<Classes>('ClassesBox');
  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
  int tableId = 16;

  for (String type in types) {
    if(classesBox.get(type) == null) {
      classesBox.put(
          type,
          Classes(type, tableId.toRadixString(16).padLeft(3, '0').toString(),
              (androidInfo.id.hashCode % 10000).abs().toString(), '0000'));
      tableId += 1;
    }
  }
}

Future<String> newId(String resource) async {
  var classesBox = await Hive.openBox<Classes>('ClassesBox');
  var tempResource = classesBox.get(resource);
  tempResource.lastId = (int.parse(tempResource.lastId) + 1).toString().padLeft(4, '0');
  classesBox.put(resource, tempResource);
  return tempResource.lastId;
}

@HiveType(typeId: 0)
class Classes {
  @HiveField(0)
  final String resourceType;

  @HiveField(1)
  final String id;

  @HiveField(2)
  final String deviceId;

  @HiveField(3)
  String lastId;

  Classes(this.resourceType, this.id, this.deviceId, this.lastId);

  factory Classes.fromJson(Map<String, dynamic> json) =>
      _$ClassesFromJson(json);
  Map<String, dynamic> toJson() => _$ClassesToJson(this);
}

// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class ClassesAdapter extends TypeAdapter<Classes> {
  @override
  final typeId = 0;

  @override
  Classes read(BinaryReader reader) {
    var numOfFields = reader.readByte();
    var fields = <int, dynamic>{
      for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Classes(
      fields[0] as String,
      fields[1] as String,
      fields[2] as String,
      fields[3] as String,
    );
  }

  @override
  void write(BinaryWriter writer, Classes obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.resourceType)
      ..writeByte(1)
      ..write(obj.id)
      ..writeByte(2)
      ..write(obj.deviceId)
      ..writeByte(3)
      ..write(obj.lastId);
  }
}

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Classes _$ClassesFromJson(Map<String, dynamic> json) {
  return Classes(
    json['resourceType'] as String,
    json['id'] as String,
    json['deviceId'] as String,
    json['lastId'] as String,
  );
}

Map<String, dynamic> _$ClassesToJson(Classes instance) => <String, dynamic>{
      'resourceType': instance.resourceType,
      'id': instance.id,
      'deviceId': instance.deviceId,
      'lastId': instance.lastId,
    };
