#!/bin/bash
# fhirToDart

python ./helpers/fhirSchemaToDart1.py
flutter pub run build_runner build
python ./helpers/fhirSchemaToDart2.py
#flutter pub run build_runner build
#python ./helpers/fhirSchemaToDart3.py
