name: flutter_fhir
description: Collect Basic Data to FHIR Server

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  json_serializable: ^3.2.5
  cupertino_icons: ^0.1.3
  grouped_buttons: ^1.0.4
  shared_preferences: ^0.5.6+1
  path_provider: ^1.6.0
  random_string: ^2.0.1
  sqflite: ^1.2.0
  path: ^1.6.4
  geolocator: ^5.2.1
  google_fonts: ^0.3.7
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  device_info: ^0.4.1+4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  hive_generator: ^0.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/prefix.json
    - assets/lang/
    - assets/smallSqlite.txt
