{
String

SubstanceAmountextension
List<ExtensionmodifierExtension
List<ExtensionamountQuantity
QuantityamountRange
Range_amountString
ElementamountType
CodeableConceptamountText
String_amountText
ElementreferenceRange
SubstanceAmount_ReferenceRangeid
SubstanceAmount_ReferenceRange.Stringextension
SubstanceAmount_ReferenceRange.List<ExtensionmodifierExtension
SubstanceAmount_ReferenceRange.List<ExtensionlowLimit
SubstanceAmount_ReferenceRange.QuantityhighLimit
SubstanceAmount_ReferenceRange.Quantity