import 'package:flutter_fhir/class/element.dart';
import 'package:flutter_fhir/class/extension.dart';
import 'package:flutter_fhir/class/narrative.dart';
import 'package:flutter_fhir/class/annotation.dart';
import 'package:flutter_fhir/class/attachment.dart';
import 'package:flutter_fhir/class/identifier.dart';
import 'package:flutter_fhir/class/codeableConcept.dart';
import 'package:flutter_fhir/class/coding.dart';
import 'package:flutter_fhir/class/quantity.dart';
import 'package:flutter_fhir/class/duration.dart';
import 'package:flutter_fhir/class/distance.dart';
import 'package:flutter_fhir/class/count.dart';
import 'package:flutter_fhir/class/money.dart';
import 'package:flutter_fhir/class/age.dart';
import 'package:flutter_fhir/class/range.dart';
import 'package:flutter_fhir/class/period.dart';
import 'package:flutter_fhir/class/ratio.dart';
import 'package:flutter_fhir/class/reference.dart';
import 'package:flutter_fhir/class/sampledData.dart';
import 'package:flutter_fhir/class/signature.dart';
import 'package:flutter_fhir/class/humanName.dart';
import 'package:flutter_fhir/class/address.dart';
import 'package:flutter_fhir/class/contactPoint.dart';
import 'package:flutter_fhir/class/timing.dart';
import 'package:flutter_fhir/class/meta.dart';
import 'package:flutter_fhir/class/contactDetail.dart';
import 'package:flutter_fhir/class/contributor.dart';
import 'package:flutter_fhir/class/dataRequirement.dart';
import 'package:flutter_fhir/class/parameterDefinition.dart';
import 'package:flutter_fhir/class/relatedArtifact.dart';
import 'package:flutter_fhir/class/triggerDefinition.dart';
import 'package:flutter_fhir/class/usageContext.dart';
import 'package:flutter_fhir/class/dosage.dart';
import 'package:flutter_fhir/class/population.dart';
import 'package:flutter_fhir/class/productShelfLife.dart';
import 'package:flutter_fhir/class/prodCharacteristic.dart';
import 'package:flutter_fhir/class/marketingStatus.dart';
import 'package:flutter_fhir/class/substanceAmount.dart';
import 'package:flutter_fhir/class/expression.dart';
import 'package:flutter_fhir/class/elementDefinition.dart';
import 'package:flutter_fhir/class/account.dart';
import 'package:flutter_fhir/class/activityDefinition.dart';
import 'package:flutter_fhir/class/adverseEvent.dart';
import 'package:flutter_fhir/class/allergyIntolerance.dart';
import 'package:flutter_fhir/class/appointment.dart';
import 'package:flutter_fhir/class/appointmentResponse.dart';
import 'package:flutter_fhir/class/auditEvent.dart';
import 'package:flutter_fhir/class/basic.dart';
import 'package:flutter_fhir/class/binary.dart';
import 'package:flutter_fhir/class/biologicallyDerivedProduct.dart';
import 'package:flutter_fhir/class/bodyStructure.dart';
import 'package:flutter_fhir/class/bundle.dart';
import 'package:flutter_fhir/class/capabilityStatement.dart';
import 'package:flutter_fhir/class/carePlan.dart';
import 'package:flutter_fhir/class/careTeam.dart';
import 'package:flutter_fhir/class/catalogEntry.dart';
import 'package:flutter_fhir/class/chargeItem.dart';
import 'package:flutter_fhir/class/chargeItemDefinition.dart';
import 'package:flutter_fhir/class/claim.dart';
import 'package:flutter_fhir/class/claimResponse.dart';
import 'package:flutter_fhir/class/clinicalImpression.dart';
import 'package:flutter_fhir/class/codeSystem.dart';
import 'package:flutter_fhir/class/communication.dart';
import 'package:flutter_fhir/class/communicationRequest.dart';
import 'package:flutter_fhir/class/compartmentDefinition.dart';
import 'package:flutter_fhir/class/composition.dart';
import 'package:flutter_fhir/class/conceptMap.dart';
import 'package:flutter_fhir/class/condition.dart';
import 'package:flutter_fhir/class/consent.dart';
import 'package:flutter_fhir/class/contract.dart';
import 'package:flutter_fhir/class/coverage.dart';
import 'package:flutter_fhir/class/coverageEligibilityRequest.dart';
import 'package:flutter_fhir/class/coverageEligibilityResponse.dart';
import 'package:flutter_fhir/class/detectedIssue.dart';
import 'package:flutter_fhir/class/device.dart';
import 'package:flutter_fhir/class/deviceDefinition.dart';
import 'package:flutter_fhir/class/deviceMetric.dart';
import 'package:flutter_fhir/class/deviceRequest.dart';
import 'package:flutter_fhir/class/deviceUseStatement.dart';
import 'package:flutter_fhir/class/diagnosticReport.dart';
import 'package:flutter_fhir/class/documentManifest.dart';
import 'package:flutter_fhir/class/documentReference.dart';
import 'package:flutter_fhir/class/effectEvidenceSynthesis.dart';
import 'package:flutter_fhir/class/encounter.dart';
import 'package:flutter_fhir/class/endpoint.dart';
import 'package:flutter_fhir/class/enrollmentRequest.dart';
import 'package:flutter_fhir/class/enrollmentResponse.dart';
import 'package:flutter_fhir/class/episodeOfCare.dart';
import 'package:flutter_fhir/class/eventDefinition.dart';
import 'package:flutter_fhir/class/evidence.dart';
import 'package:flutter_fhir/class/evidenceVariable.dart';
import 'package:flutter_fhir/class/exampleScenario.dart';
import 'package:flutter_fhir/class/explanationOfBenefit.dart';
import 'package:flutter_fhir/class/familyMemberHistory.dart';
import 'package:flutter_fhir/class/flag.dart';
import 'package:flutter_fhir/class/goal.dart';
import 'package:flutter_fhir/class/graphDefinition.dart';
import 'package:flutter_fhir/class/group.dart';
import 'package:flutter_fhir/class/guidanceResponse.dart';
import 'package:flutter_fhir/class/healthcareService.dart';
import 'package:flutter_fhir/class/imagingStudy.dart';
import 'package:flutter_fhir/class/immunization.dart';
import 'package:flutter_fhir/class/immunizationEvaluation.dart';
import 'package:flutter_fhir/class/immunizationRecommendation.dart';
import 'package:flutter_fhir/class/implementationGuide.dart';
import 'package:flutter_fhir/class/insurancePlan.dart';
import 'package:flutter_fhir/class/invoice.dart';
import 'package:flutter_fhir/class/library.dart';
import 'package:flutter_fhir/class/linkage.dart';
import 'package:flutter_fhir/class/lists.dart';
import 'package:flutter_fhir/class/location.dart';
import 'package:flutter_fhir/class/measure.dart';
import 'package:flutter_fhir/class/measureReport.dart';
import 'package:flutter_fhir/class/media.dart';
import 'package:flutter_fhir/class/medication.dart';
import 'package:flutter_fhir/class/medicationAdministration.dart';
import 'package:flutter_fhir/class/medicationDispense.dart';
import 'package:flutter_fhir/class/medicationKnowledge.dart';
import 'package:flutter_fhir/class/medicationRequest.dart';
import 'package:flutter_fhir/class/medicationStatement.dart';
import 'package:flutter_fhir/class/medicinalProduct.dart';
import 'package:flutter_fhir/class/medicinalProductAuthorization.dart';
import 'package:flutter_fhir/class/medicinalProductContraindication.dart';
import 'package:flutter_fhir/class/medicinalProductIndication.dart';
import 'package:flutter_fhir/class/medicinalProductIngredient.dart';
import 'package:flutter_fhir/class/medicinalProductInteraction.dart';
import 'package:flutter_fhir/class/medicinalProductManufactured.dart';
import 'package:flutter_fhir/class/medicinalProductPackaged.dart';
import 'package:flutter_fhir/class/medicinalProductPharmaceutical.dart';
import 'package:flutter_fhir/class/medicinalProductUndesirableEffect.dart';
import 'package:flutter_fhir/class/messageDefinition.dart';
import 'package:flutter_fhir/class/messageHeader.dart';
import 'package:flutter_fhir/class/molecularSequence.dart';
import 'package:flutter_fhir/class/namingSystem.dart';
import 'package:flutter_fhir/class/nutritionOrder.dart';
import 'package:flutter_fhir/class/observation.dart';
import 'package:flutter_fhir/class/observationDefinition.dart';
import 'package:flutter_fhir/class/operationDefinition.dart';
import 'package:flutter_fhir/class/operationOutcome.dart';
import 'package:flutter_fhir/class/organization.dart';
import 'package:flutter_fhir/class/organizationAffiliation.dart';
import 'package:flutter_fhir/class/parameters.dart';
import 'package:flutter_fhir/class/patient.dart';
import 'package:flutter_fhir/class/paymentNotice.dart';
import 'package:flutter_fhir/class/paymentReconciliation.dart';
import 'package:flutter_fhir/class/person.dart';
import 'package:flutter_fhir/class/planDefinition.dart';
import 'package:flutter_fhir/class/practitioner.dart';
import 'package:flutter_fhir/class/practitionerRole.dart';
import 'package:flutter_fhir/class/procedure.dart';
import 'package:flutter_fhir/class/provenance.dart';
import 'package:flutter_fhir/class/questionnaire.dart';
import 'package:flutter_fhir/class/questionnaireResponse.dart';
import 'package:flutter_fhir/class/relatedPerson.dart';
import 'package:flutter_fhir/class/requestGroup.dart';
import 'package:flutter_fhir/class/researchDefinition.dart';
import 'package:flutter_fhir/class/researchElementDefinition.dart';
import 'package:flutter_fhir/class/researchStudy.dart';
import 'package:flutter_fhir/class/researchSubject.dart';
import 'package:flutter_fhir/class/riskAssessment.dart';
import 'package:flutter_fhir/class/riskEvidenceSynthesis.dart';
import 'package:flutter_fhir/class/schedule.dart';
import 'package:flutter_fhir/class/searchParameter.dart';
import 'package:flutter_fhir/class/serviceRequest.dart';
import 'package:flutter_fhir/class/slot.dart';
import 'package:flutter_fhir/class/specimen.dart';
import 'package:flutter_fhir/class/specimenDefinition.dart';
import 'package:flutter_fhir/class/structureDefinition.dart';
import 'package:flutter_fhir/class/structureMap.dart';
import 'package:flutter_fhir/class/subscription.dart';
import 'package:flutter_fhir/class/substance.dart';
import 'package:flutter_fhir/class/substanceNucleicAcid.dart';
import 'package:flutter_fhir/class/substancePolymer.dart';
import 'package:flutter_fhir/class/substanceProtein.dart';
import 'package:flutter_fhir/class/substanceReferenceInformation.dart';
import 'package:flutter_fhir/class/substanceSourceMaterial.dart';
import 'package:flutter_fhir/class/substanceSpecification.dart';
import 'package:flutter_fhir/class/supplyDelivery.dart';
import 'package:flutter_fhir/class/supplyRequest.dart';
import 'package:flutter_fhir/class/task.dart';
import 'package:flutter_fhir/class/terminologyCapabilities.dart';
import 'package:flutter_fhir/class/testReport.dart';
import 'package:flutter_fhir/class/testScript.dart';
import 'package:flutter_fhir/class/valueSet.dart';
import 'package:flutter_fhir/class/verificationResult.dart';
import 'package:flutter_fhir/class/visionPrescription.dart';

dynamic ResourceTypes(String type, Map<String, dynamic> json) {
  if(type == 'Element') return (new Element.fromJson(json));
  if(type == 'Extension') return (new Extension.fromJson(json));
  if(type == 'Narrative') return (new Narrative.fromJson(json));
  if(type == 'Annotation') return (new Annotation.fromJson(json));
  if(type == 'Attachment') return (new Attachment.fromJson(json));
  if(type == 'Identifier') return (new Identifier.fromJson(json));
  if(type == 'CodeableConcept') return (new CodeableConcept.fromJson(json));
  if(type == 'Coding') return (new Coding.fromJson(json));
  if(type == 'Quantity') return (new Quantity.fromJson(json));
  if(type == 'Duration') return (new Duration.fromJson(json));
  if(type == 'Distance') return (new Distance.fromJson(json));
  if(type == 'Count') return (new Count.fromJson(json));
  if(type == 'Money') return (new Money.fromJson(json));
  if(type == 'Age') return (new Age.fromJson(json));
  if(type == 'Range') return (new Range.fromJson(json));
  if(type == 'Period') return (new Period.fromJson(json));
  if(type == 'Ratio') return (new Ratio.fromJson(json));
  if(type == 'Reference') return (new Reference.fromJson(json));
  if(type == 'SampledData') return (new SampledData.fromJson(json));
  if(type == 'Signature') return (new Signature.fromJson(json));
  if(type == 'HumanName') return (new HumanName.fromJson(json));
  if(type == 'Address') return (new Address.fromJson(json));
  if(type == 'ContactPoint') return (new ContactPoint.fromJson(json));
  if(type == 'Timing') return (new Timing.fromJson(json));
  if(type == 'Meta') return (new Meta.fromJson(json));
  if(type == 'ContactDetail') return (new ContactDetail.fromJson(json));
  if(type == 'Contributor') return (new Contributor.fromJson(json));
  if(type == 'DataRequirement') return (new DataRequirement.fromJson(json));
  if(type == 'ParameterDefinition') return (new ParameterDefinition.fromJson(json));
  if(type == 'RelatedArtifact') return (new RelatedArtifact.fromJson(json));
  if(type == 'TriggerDefinition') return (new TriggerDefinition.fromJson(json));
  if(type == 'UsageContext') return (new UsageContext.fromJson(json));
  if(type == 'Dosage') return (new Dosage.fromJson(json));
  if(type == 'Population') return (new Population.fromJson(json));
  if(type == 'ProductShelfLife') return (new ProductShelfLife.fromJson(json));
  if(type == 'ProdCharacteristic') return (new ProdCharacteristic.fromJson(json));
  if(type == 'MarketingStatus') return (new MarketingStatus.fromJson(json));
  if(type == 'SubstanceAmount') return (new SubstanceAmount.fromJson(json));
  if(type == 'Expression') return (new Expression.fromJson(json));
  if(type == 'ElementDefinition') return (new ElementDefinition.fromJson(json));
  if(type == 'Account') return (new Account.fromJson(json));
  if(type == 'ActivityDefinition') return (new ActivityDefinition.fromJson(json));
  if(type == 'AdverseEvent') return (new AdverseEvent.fromJson(json));
  if(type == 'AllergyIntolerance') return (new AllergyIntolerance.fromJson(json));
  if(type == 'Appointment') return (new Appointment.fromJson(json));
  if(type == 'AppointmentResponse') return (new AppointmentResponse.fromJson(json));
  if(type == 'AuditEvent') return (new AuditEvent.fromJson(json));
  if(type == 'Basic') return (new Basic.fromJson(json));
  if(type == 'Binary') return (new Binary.fromJson(json));
  if(type == 'BiologicallyDerivedProduct') return (new BiologicallyDerivedProduct.fromJson(json));
  if(type == 'BodyStructure') return (new BodyStructure.fromJson(json));
  if(type == 'Bundle') return (new Bundle.fromJson(json));
  if(type == 'CapabilityStatement') return (new CapabilityStatement.fromJson(json));
  if(type == 'CarePlan') return (new CarePlan.fromJson(json));
  if(type == 'CareTeam') return (new CareTeam.fromJson(json));
  if(type == 'CatalogEntry') return (new CatalogEntry.fromJson(json));
  if(type == 'ChargeItem') return (new ChargeItem.fromJson(json));
  if(type == 'ChargeItemDefinition') return (new ChargeItemDefinition.fromJson(json));
  if(type == 'Claim') return (new Claim.fromJson(json));
  if(type == 'ClaimResponse') return (new ClaimResponse.fromJson(json));
  if(type == 'ClinicalImpression') return (new ClinicalImpression.fromJson(json));
  if(type == 'CodeSystem') return (new CodeSystem.fromJson(json));
  if(type == 'Communication') return (new Communication.fromJson(json));
  if(type == 'CommunicationRequest') return (new CommunicationRequest.fromJson(json));
  if(type == 'CompartmentDefinition') return (new CompartmentDefinition.fromJson(json));
  if(type == 'Composition') return (new Composition.fromJson(json));
  if(type == 'ConceptMap') return (new ConceptMap.fromJson(json));
  if(type == 'Condition') return (new Condition.fromJson(json));
  if(type == 'Consent') return (new Consent.fromJson(json));
  if(type == 'Contract') return (new Contract.fromJson(json));
  if(type == 'Coverage') return (new Coverage.fromJson(json));
  if(type == 'CoverageEligibilityRequest') return (new CoverageEligibilityRequest.fromJson(json));
  if(type == 'CoverageEligibilityResponse') return (new CoverageEligibilityResponse.fromJson(json));
  if(type == 'DetectedIssue') return (new DetectedIssue.fromJson(json));
  if(type == 'Device') return (new Device.fromJson(json));
  if(type == 'DeviceDefinition') return (new DeviceDefinition.fromJson(json));
  if(type == 'DeviceMetric') return (new DeviceMetric.fromJson(json));
  if(type == 'DeviceRequest') return (new DeviceRequest.fromJson(json));
  if(type == 'DeviceUseStatement') return (new DeviceUseStatement.fromJson(json));
  if(type == 'DiagnosticReport') return (new DiagnosticReport.fromJson(json));
  if(type == 'DocumentManifest') return (new DocumentManifest.fromJson(json));
  if(type == 'DocumentReference') return (new DocumentReference.fromJson(json));
  if(type == 'EffectEvidenceSynthesis') return (new EffectEvidenceSynthesis.fromJson(json));
  if(type == 'Encounter') return (new Encounter.fromJson(json));
  if(type == 'Endpoint') return (new Endpoint.fromJson(json));
  if(type == 'EnrollmentRequest') return (new EnrollmentRequest.fromJson(json));
  if(type == 'EnrollmentResponse') return (new EnrollmentResponse.fromJson(json));
  if(type == 'EpisodeOfCare') return (new EpisodeOfCare.fromJson(json));
  if(type == 'EventDefinition') return (new EventDefinition.fromJson(json));
  if(type == 'Evidence') return (new Evidence.fromJson(json));
  if(type == 'EvidenceVariable') return (new EvidenceVariable.fromJson(json));
  if(type == 'ExampleScenario') return (new ExampleScenario.fromJson(json));
  if(type == 'ExplanationOfBenefit') return (new ExplanationOfBenefit.fromJson(json));
  if(type == 'FamilyMemberHistory') return (new FamilyMemberHistory.fromJson(json));
  if(type == 'Flag') return (new Flag.fromJson(json));
  if(type == 'Goal') return (new Goal.fromJson(json));
  if(type == 'GraphDefinition') return (new GraphDefinition.fromJson(json));
  if(type == 'Group') return (new Group.fromJson(json));
  if(type == 'GuidanceResponse') return (new GuidanceResponse.fromJson(json));
  if(type == 'HealthcareService') return (new HealthcareService.fromJson(json));
  if(type == 'ImagingStudy') return (new ImagingStudy.fromJson(json));
  if(type == 'Immunization') return (new Immunization.fromJson(json));
  if(type == 'ImmunizationEvaluation') return (new ImmunizationEvaluation.fromJson(json));
  if(type == 'ImmunizationRecommendation') return (new ImmunizationRecommendation.fromJson(json));
  if(type == 'ImplementationGuide') return (new ImplementationGuide.fromJson(json));
  if(type == 'InsurancePlan') return (new InsurancePlan.fromJson(json));
  if(type == 'Invoice') return (new Invoice.fromJson(json));
  if(type == 'Library') return (new Library.fromJson(json));
  if(type == 'Linkage') return (new Linkage.fromJson(json));
  if(type == 'Lists') return (new Lists.fromJson(json));
  if(type == 'Location') return (new Location.fromJson(json));
  if(type == 'Measure') return (new Measure.fromJson(json));
  if(type == 'MeasureReport') return (new MeasureReport.fromJson(json));
  if(type == 'Media') return (new Media.fromJson(json));
  if(type == 'Medication') return (new Medication.fromJson(json));
  if(type == 'MedicationAdministration') return (new MedicationAdministration.fromJson(json));
  if(type == 'MedicationDispense') return (new MedicationDispense.fromJson(json));
  if(type == 'MedicationKnowledge') return (new MedicationKnowledge.fromJson(json));
  if(type == 'MedicationRequest') return (new MedicationRequest.fromJson(json));
  if(type == 'MedicationStatement') return (new MedicationStatement.fromJson(json));
  if(type == 'MedicinalProduct') return (new MedicinalProduct.fromJson(json));
  if(type == 'MedicinalProductAuthorization') return (new MedicinalProductAuthorization.fromJson(json));
  if(type == 'MedicinalProductContraindication') return (new MedicinalProductContraindication.fromJson(json));
  if(type == 'MedicinalProductIndication') return (new MedicinalProductIndication.fromJson(json));
  if(type == 'MedicinalProductIngredient') return (new MedicinalProductIngredient.fromJson(json));
  if(type == 'MedicinalProductInteraction') return (new MedicinalProductInteraction.fromJson(json));
  if(type == 'MedicinalProductManufactured') return (new MedicinalProductManufactured.fromJson(json));
  if(type == 'MedicinalProductPackaged') return (new MedicinalProductPackaged.fromJson(json));
  if(type == 'MedicinalProductPharmaceutical') return (new MedicinalProductPharmaceutical.fromJson(json));
  if(type == 'MedicinalProductUndesirableEffect') return (new MedicinalProductUndesirableEffect.fromJson(json));
  if(type == 'MessageDefinition') return (new MessageDefinition.fromJson(json));
  if(type == 'MessageHeader') return (new MessageHeader.fromJson(json));
  if(type == 'MolecularSequence') return (new MolecularSequence.fromJson(json));
  if(type == 'NamingSystem') return (new NamingSystem.fromJson(json));
  if(type == 'NutritionOrder') return (new NutritionOrder.fromJson(json));
  if(type == 'Observation') return (new Observation.fromJson(json));
  if(type == 'ObservationDefinition') return (new ObservationDefinition.fromJson(json));
  if(type == 'OperationDefinition') return (new OperationDefinition.fromJson(json));
  if(type == 'OperationOutcome') return (new OperationOutcome.fromJson(json));
  if(type == 'Organization') return (new Organization.fromJson(json));
  if(type == 'OrganizationAffiliation') return (new OrganizationAffiliation.fromJson(json));
  if(type == 'Parameters') return (new Parameters.fromJson(json));
  if(type == 'Patient') return (new Patient.fromJson(json));
  if(type == 'PaymentNotice') return (new PaymentNotice.fromJson(json));
  if(type == 'PaymentReconciliation') return (new PaymentReconciliation.fromJson(json));
  if(type == 'Person') return (new Person.fromJson(json));
  if(type == 'PlanDefinition') return (new PlanDefinition.fromJson(json));
  if(type == 'Practitioner') return (new Practitioner.fromJson(json));
  if(type == 'PractitionerRole') return (new PractitionerRole.fromJson(json));
  if(type == 'Procedure') return (new Procedure.fromJson(json));
  if(type == 'Provenance') return (new Provenance.fromJson(json));
  if(type == 'Questionnaire') return (new Questionnaire.fromJson(json));
  if(type == 'QuestionnaireResponse') return (new QuestionnaireResponse.fromJson(json));
  if(type == 'RelatedPerson') return (new RelatedPerson.fromJson(json));
  if(type == 'RequestGroup') return (new RequestGroup.fromJson(json));
  if(type == 'ResearchDefinition') return (new ResearchDefinition.fromJson(json));
  if(type == 'ResearchElementDefinition') return (new ResearchElementDefinition.fromJson(json));
  if(type == 'ResearchStudy') return (new ResearchStudy.fromJson(json));
  if(type == 'ResearchSubject') return (new ResearchSubject.fromJson(json));
  if(type == 'RiskAssessment') return (new RiskAssessment.fromJson(json));
  if(type == 'RiskEvidenceSynthesis') return (new RiskEvidenceSynthesis.fromJson(json));
  if(type == 'Schedule') return (new Schedule.fromJson(json));
  if(type == 'SearchParameter') return (new SearchParameter.fromJson(json));
  if(type == 'ServiceRequest') return (new ServiceRequest.fromJson(json));
  if(type == 'Slot') return (new Slot.fromJson(json));
  if(type == 'Specimen') return (new Specimen.fromJson(json));
  if(type == 'SpecimenDefinition') return (new SpecimenDefinition.fromJson(json));
  if(type == 'StructureDefinition') return (new StructureDefinition.fromJson(json));
  if(type == 'StructureMap') return (new StructureMap.fromJson(json));
  if(type == 'Subscription') return (new Subscription.fromJson(json));
  if(type == 'Substance') return (new Substance.fromJson(json));
  if(type == 'SubstanceNucleicAcid') return (new SubstanceNucleicAcid.fromJson(json));
  if(type == 'SubstancePolymer') return (new SubstancePolymer.fromJson(json));
  if(type == 'SubstanceProtein') return (new SubstanceProtein.fromJson(json));
  if(type == 'SubstanceReferenceInformation') return (new SubstanceReferenceInformation.fromJson(json));
  if(type == 'SubstanceSourceMaterial') return (new SubstanceSourceMaterial.fromJson(json));
  if(type == 'SubstanceSpecification') return (new SubstanceSpecification.fromJson(json));
  if(type == 'SupplyDelivery') return (new SupplyDelivery.fromJson(json));
  if(type == 'SupplyRequest') return (new SupplyRequest.fromJson(json));
  if(type == 'Task') return (new Task.fromJson(json));
  if(type == 'TerminologyCapabilities') return (new TerminologyCapabilities.fromJson(json));
  if(type == 'TestReport') return (new TestReport.fromJson(json));
  if(type == 'TestScript') return (new TestScript.fromJson(json));
  if(type == 'ValueSet') return (new ValueSet.fromJson(json));
  if(type == 'VerificationResult') return (new VerificationResult.fromJson(json));
  if(type == 'VisionPrescription') return (new VisionPrescription.fromJson(json));
}
